# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.5

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/owg/Documents/homework/Graphics/assignments/game_phase1/asteroids_template

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/owg/Documents/homework/Graphics/assignments/game_phase1/asteroids_template

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/owg/Documents/homework/Graphics/assignments/game_phase1/asteroids_template/CMakeFiles /home/owg/Documents/homework/Graphics/assignments/game_phase1/asteroids_template/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/owg/Documents/homework/Graphics/assignments/game_phase1/asteroids_template/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named glad

# Build rule for target.
glad: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 glad
.PHONY : glad

# fast build rule for target.
glad/fast:
	$(MAKE) -f CMakeFiles/glad.dir/build.make CMakeFiles/glad.dir/build
.PHONY : glad/fast

#=============================================================================
# Target rules for targets named asteroids

# Build rule for target.
asteroids: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 asteroids
.PHONY : asteroids

# fast build rule for target.
asteroids/fast:
	$(MAKE) -f CMakeFiles/asteroids.dir/build.make CMakeFiles/asteroids.dir/build
.PHONY : asteroids/fast

#=============================================================================
# Target rules for targets named glfw

# Build rule for target.
glfw: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 glfw
.PHONY : glfw

# fast build rule for target.
glfw/fast:
	$(MAKE) -f glfw-3.2/src/CMakeFiles/glfw.dir/build.make glfw-3.2/src/CMakeFiles/glfw.dir/build
.PHONY : glfw/fast

#=============================================================================
# Target rules for targets named docs

# Build rule for target.
docs: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 docs
.PHONY : docs

# fast build rule for target.
docs/fast:
	$(MAKE) -f glfw-3.2/docs/CMakeFiles/docs.dir/build.make glfw-3.2/docs/CMakeFiles/docs.dir/build
.PHONY : docs/fast

glfw-3.2/deps/glad.o: glfw-3.2/deps/glad.c.o

.PHONY : glfw-3.2/deps/glad.o

# target to build an object file
glfw-3.2/deps/glad.c.o:
	$(MAKE) -f CMakeFiles/glad.dir/build.make CMakeFiles/glad.dir/glfw-3.2/deps/glad.c.o
.PHONY : glfw-3.2/deps/glad.c.o

glfw-3.2/deps/glad.i: glfw-3.2/deps/glad.c.i

.PHONY : glfw-3.2/deps/glad.i

# target to preprocess a source file
glfw-3.2/deps/glad.c.i:
	$(MAKE) -f CMakeFiles/glad.dir/build.make CMakeFiles/glad.dir/glfw-3.2/deps/glad.c.i
.PHONY : glfw-3.2/deps/glad.c.i

glfw-3.2/deps/glad.s: glfw-3.2/deps/glad.c.s

.PHONY : glfw-3.2/deps/glad.s

# target to generate assembly for a file
glfw-3.2/deps/glad.c.s:
	$(MAKE) -f CMakeFiles/glad.dir/build.make CMakeFiles/glad.dir/glfw-3.2/deps/glad.c.s
.PHONY : glfw-3.2/deps/glad.c.s

shaders/shader.o: shaders/shader.cpp.o

.PHONY : shaders/shader.o

# target to build an object file
shaders/shader.cpp.o:
	$(MAKE) -f CMakeFiles/asteroids.dir/build.make CMakeFiles/asteroids.dir/shaders/shader.cpp.o
.PHONY : shaders/shader.cpp.o

shaders/shader.i: shaders/shader.cpp.i

.PHONY : shaders/shader.i

# target to preprocess a source file
shaders/shader.cpp.i:
	$(MAKE) -f CMakeFiles/asteroids.dir/build.make CMakeFiles/asteroids.dir/shaders/shader.cpp.i
.PHONY : shaders/shader.cpp.i

shaders/shader.s: shaders/shader.cpp.s

.PHONY : shaders/shader.s

# target to generate assembly for a file
shaders/shader.cpp.s:
	$(MAKE) -f CMakeFiles/asteroids.dir/build.make CMakeFiles/asteroids.dir/shaders/shader.cpp.s
.PHONY : shaders/shader.cpp.s

source/Asteroid.o: source/Asteroid.cpp.o

.PHONY : source/Asteroid.o

# target to build an object file
source/Asteroid.cpp.o:
	$(MAKE) -f CMakeFiles/asteroids.dir/build.make CMakeFiles/asteroids.dir/source/Asteroid.cpp.o
.PHONY : source/Asteroid.cpp.o

source/Asteroid.i: source/Asteroid.cpp.i

.PHONY : source/Asteroid.i

# target to preprocess a source file
source/Asteroid.cpp.i:
	$(MAKE) -f CMakeFiles/asteroids.dir/build.make CMakeFiles/asteroids.dir/source/Asteroid.cpp.i
.PHONY : source/Asteroid.cpp.i

source/Asteroid.s: source/Asteroid.cpp.s

.PHONY : source/Asteroid.s

# target to generate assembly for a file
source/Asteroid.cpp.s:
	$(MAKE) -f CMakeFiles/asteroids.dir/build.make CMakeFiles/asteroids.dir/source/Asteroid.cpp.s
.PHONY : source/Asteroid.cpp.s

source/Background.o: source/Background.cpp.o

.PHONY : source/Background.o

# target to build an object file
source/Background.cpp.o:
	$(MAKE) -f CMakeFiles/asteroids.dir/build.make CMakeFiles/asteroids.dir/source/Background.cpp.o
.PHONY : source/Background.cpp.o

source/Background.i: source/Background.cpp.i

.PHONY : source/Background.i

# target to preprocess a source file
source/Background.cpp.i:
	$(MAKE) -f CMakeFiles/asteroids.dir/build.make CMakeFiles/asteroids.dir/source/Background.cpp.i
.PHONY : source/Background.cpp.i

source/Background.s: source/Background.cpp.s

.PHONY : source/Background.s

# target to generate assembly for a file
source/Background.cpp.s:
	$(MAKE) -f CMakeFiles/asteroids.dir/build.make CMakeFiles/asteroids.dir/source/Background.cpp.s
.PHONY : source/Background.cpp.s

source/Bullet.o: source/Bullet.cpp.o

.PHONY : source/Bullet.o

# target to build an object file
source/Bullet.cpp.o:
	$(MAKE) -f CMakeFiles/asteroids.dir/build.make CMakeFiles/asteroids.dir/source/Bullet.cpp.o
.PHONY : source/Bullet.cpp.o

source/Bullet.i: source/Bullet.cpp.i

.PHONY : source/Bullet.i

# target to preprocess a source file
source/Bullet.cpp.i:
	$(MAKE) -f CMakeFiles/asteroids.dir/build.make CMakeFiles/asteroids.dir/source/Bullet.cpp.i
.PHONY : source/Bullet.cpp.i

source/Bullet.s: source/Bullet.cpp.s

.PHONY : source/Bullet.s

# target to generate assembly for a file
source/Bullet.cpp.s:
	$(MAKE) -f CMakeFiles/asteroids.dir/build.make CMakeFiles/asteroids.dir/source/Bullet.cpp.s
.PHONY : source/Bullet.cpp.s

source/Explosion.o: source/Explosion.cpp.o

.PHONY : source/Explosion.o

# target to build an object file
source/Explosion.cpp.o:
	$(MAKE) -f CMakeFiles/asteroids.dir/build.make CMakeFiles/asteroids.dir/source/Explosion.cpp.o
.PHONY : source/Explosion.cpp.o

source/Explosion.i: source/Explosion.cpp.i

.PHONY : source/Explosion.i

# target to preprocess a source file
source/Explosion.cpp.i:
	$(MAKE) -f CMakeFiles/asteroids.dir/build.make CMakeFiles/asteroids.dir/source/Explosion.cpp.i
.PHONY : source/Explosion.cpp.i

source/Explosion.s: source/Explosion.cpp.s

.PHONY : source/Explosion.s

# target to generate assembly for a file
source/Explosion.cpp.s:
	$(MAKE) -f CMakeFiles/asteroids.dir/build.make CMakeFiles/asteroids.dir/source/Explosion.cpp.s
.PHONY : source/Explosion.cpp.s

source/Ship.o: source/Ship.cpp.o

.PHONY : source/Ship.o

# target to build an object file
source/Ship.cpp.o:
	$(MAKE) -f CMakeFiles/asteroids.dir/build.make CMakeFiles/asteroids.dir/source/Ship.cpp.o
.PHONY : source/Ship.cpp.o

source/Ship.i: source/Ship.cpp.i

.PHONY : source/Ship.i

# target to preprocess a source file
source/Ship.cpp.i:
	$(MAKE) -f CMakeFiles/asteroids.dir/build.make CMakeFiles/asteroids.dir/source/Ship.cpp.i
.PHONY : source/Ship.cpp.i

source/Ship.s: source/Ship.cpp.s

.PHONY : source/Ship.s

# target to generate assembly for a file
source/Ship.cpp.s:
	$(MAKE) -f CMakeFiles/asteroids.dir/build.make CMakeFiles/asteroids.dir/source/Ship.cpp.s
.PHONY : source/Ship.cpp.s

source/main.o: source/main.cpp.o

.PHONY : source/main.o

# target to build an object file
source/main.cpp.o:
	$(MAKE) -f CMakeFiles/asteroids.dir/build.make CMakeFiles/asteroids.dir/source/main.cpp.o
.PHONY : source/main.cpp.o

source/main.i: source/main.cpp.i

.PHONY : source/main.i

# target to preprocess a source file
source/main.cpp.i:
	$(MAKE) -f CMakeFiles/asteroids.dir/build.make CMakeFiles/asteroids.dir/source/main.cpp.i
.PHONY : source/main.cpp.i

source/main.s: source/main.cpp.s

.PHONY : source/main.s

# target to generate assembly for a file
source/main.cpp.s:
	$(MAKE) -f CMakeFiles/asteroids.dir/build.make CMakeFiles/asteroids.dir/source/main.cpp.s
.PHONY : source/main.cpp.s

source/stb/stb_image.o: source/stb/stb_image.cpp.o

.PHONY : source/stb/stb_image.o

# target to build an object file
source/stb/stb_image.cpp.o:
	$(MAKE) -f CMakeFiles/asteroids.dir/build.make CMakeFiles/asteroids.dir/source/stb/stb_image.cpp.o
.PHONY : source/stb/stb_image.cpp.o

source/stb/stb_image.i: source/stb/stb_image.cpp.i

.PHONY : source/stb/stb_image.i

# target to preprocess a source file
source/stb/stb_image.cpp.i:
	$(MAKE) -f CMakeFiles/asteroids.dir/build.make CMakeFiles/asteroids.dir/source/stb/stb_image.cpp.i
.PHONY : source/stb/stb_image.cpp.i

source/stb/stb_image.s: source/stb/stb_image.cpp.s

.PHONY : source/stb/stb_image.s

# target to generate assembly for a file
source/stb/stb_image.cpp.s:
	$(MAKE) -f CMakeFiles/asteroids.dir/build.make CMakeFiles/asteroids.dir/source/stb/stb_image.cpp.s
.PHONY : source/stb/stb_image.cpp.s

source/utils/geometryhelpers.o: source/utils/geometryhelpers.cpp.o

.PHONY : source/utils/geometryhelpers.o

# target to build an object file
source/utils/geometryhelpers.cpp.o:
	$(MAKE) -f CMakeFiles/asteroids.dir/build.make CMakeFiles/asteroids.dir/source/utils/geometryhelpers.cpp.o
.PHONY : source/utils/geometryhelpers.cpp.o

source/utils/geometryhelpers.i: source/utils/geometryhelpers.cpp.i

.PHONY : source/utils/geometryhelpers.i

# target to preprocess a source file
source/utils/geometryhelpers.cpp.i:
	$(MAKE) -f CMakeFiles/asteroids.dir/build.make CMakeFiles/asteroids.dir/source/utils/geometryhelpers.cpp.i
.PHONY : source/utils/geometryhelpers.cpp.i

source/utils/geometryhelpers.s: source/utils/geometryhelpers.cpp.s

.PHONY : source/utils/geometryhelpers.s

# target to generate assembly for a file
source/utils/geometryhelpers.cpp.s:
	$(MAKE) -f CMakeFiles/asteroids.dir/build.make CMakeFiles/asteroids.dir/source/utils/geometryhelpers.cpp.s
.PHONY : source/utils/geometryhelpers.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... glad"
	@echo "... asteroids"
	@echo "... glfw"
	@echo "... docs"
	@echo "... glfw-3.2/deps/glad.o"
	@echo "... glfw-3.2/deps/glad.i"
	@echo "... glfw-3.2/deps/glad.s"
	@echo "... shaders/shader.o"
	@echo "... shaders/shader.i"
	@echo "... shaders/shader.s"
	@echo "... source/Asteroid.o"
	@echo "... source/Asteroid.i"
	@echo "... source/Asteroid.s"
	@echo "... source/Background.o"
	@echo "... source/Background.i"
	@echo "... source/Background.s"
	@echo "... source/Bullet.o"
	@echo "... source/Bullet.i"
	@echo "... source/Bullet.s"
	@echo "... source/Explosion.o"
	@echo "... source/Explosion.i"
	@echo "... source/Explosion.s"
	@echo "... source/Ship.o"
	@echo "... source/Ship.i"
	@echo "... source/Ship.s"
	@echo "... source/main.o"
	@echo "... source/main.i"
	@echo "... source/main.s"
	@echo "... source/stb/stb_image.o"
	@echo "... source/stb/stb_image.i"
	@echo "... source/stb/stb_image.s"
	@echo "... source/utils/geometryhelpers.o"
	@echo "... source/utils/geometryhelpers.i"
	@echo "... source/utils/geometryhelpers.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

